#!/usr/bin/env sh

export GUI=1
export NNN_OPTS='eEoRx'
export NNN_BMS='d:~/downloads;p:~/pictures;t:/tmp;'
#export NNN_OPENER=$HOME/.config/nnn/plugins/nuke
export NNN_PLUG='b:bookmarks;c:chksum;d:diffs;g:_tig*;t:treeview.local;%:tmux-opener-horizontal;":tmux-opener-vertical;w:tmux-opener-new-window;'

n() {
    # Block nesting of nnn
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -gt 0 ]
    then
        exit
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # NOTE: NNN_TMPFILE is fixed, should not be modified
    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
